services:
  api:
    build:
      context: ./src
      dockerfile: Inventory.Api/Dockerfile
    ports:
      - "9080:8080"
      - "9081:8081"
    depends_on:
      - sqlserver  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "redarbor.2024"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" 
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d/init-db 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
