services:
  api:
    image: inventory_system
    build:
      context: ../.. 
      dockerfile: ./docker/App/Dockerfile
    ports:
      - "5000:80"  
    depends_on:
      - sqlserver  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "redarbor.2024"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433" 
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
